### ISSUE TITLE
-[UIScreen isiPhoneX]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by ghost** [HarshilShah/NotchKit#2]
Not really sure why this is happening. I set the extension and computed property to `public` and it didn't fix anything. Happens when `updateCornerRadii()` gets called in `layoutSubviews()`.

**Temporary fix:** I added this
```swift
private var isiPhoneX: Bool {
      return screen.nativeBounds.height == 2436 && screen.nativeBounds.width  == 1125
}
```
to `NotchKitWindow` and replaced all instances of `screen.isiPhoneX` with `isiPhoneX`.

**Comment by HarshilShah** [comment]
This is a weird bug. I don't use selectors much except with dealing with Apple's own API, so I've never seen this. Stack Overflow doesn't seem to help much either; most answers deal the method signature/parameters or selector syntax.

Best guess I have is that maybe there's a private `isiPhoneX` UIScreen variable in UIKit, and somehow the compiler decides that should be called, and is flagging because being private that cannot be called.

Anyways, since your solution works, I've implemented this, and this bug will be fixed in the next release. Thanks for filing an issue!
